Controllers/ProductCategoryController.cs
using BuildingShopFront.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Diagnostics.Eventing.Reader;
using System.Text.Json.Nodes;

namespace BuildingShopFront.Controllers
{
    public class ProductCategoryController:Controller
    {
        private readonly HttpClient _httpClient;
        public ProductCategoryController(HttpClient httpClient)
        {
            _httpClient = httpClient;
        }
        public async Task<IActionResult> Index(string? searchString,
            int page=1)
        {
            return View(await GetData("","",page));
        }
        public async Task<IActionResult> Search(string? searchString,
            int page = 1)
        {
            return PartialView("_CategoriesTable", await GetData("", searchString, page));
        }
        private async Task<Object> GetData(
            string? sortOrder, string? searchString, int page=1)
        {
            var response = await _httpClient
                .GetAsync("api/ProductCategory/sort" +
                $"?sortOrder={sortOrder}&searchString={searchString}&page={page}");
            response.EnsureSuccessStatusCode();
            var content = await response.Content.ReadAsStringAsync();
            JObject json = JObject.Parse(content);
            List<ProductCategory> categories = new List<ProductCategory>();
            foreach (var item in json["items"])
            {
                categories.Add(JsonConvert.DeserializeObject
                    <ProductCategory>(item.ToString()));
            }
            ViewBag.CurrentPage = json["currentPage"];
            ViewBag.TotalPages = json["totalPages"];
            ViewBag.TotalCount = json["totalCount"];
            return categories;
        }
        public async Task<object> Add(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                var requestData = new { name = name };
                var content1 = JsonContent.Create(requestData);
                var response1 = await _httpClient.PostAsync
                    ("api/ProductCategory", content1);
                response1.EnsureSuccessStatusCode();
            }
            return PartialView("_CategoriesTable",await GetData("", ""));
        }
        [HttpPost]
        public async Task<IActionResult> Update(long id,string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                var requestData = new { id = id, name = name };
                var content = JsonContent.Create(requestData);
                var response = await _httpClient.PutAsync
                    ("api/ProductCategory", content);
                response.EnsureSuccessStatusCode();
            }
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Delete(long id)
        {
            var response = await _httpClient.DeleteAsync
                ($"api/ProductCategory/{id}");
            response?.EnsureSuccessStatusCode();
            return RedirectToAction("Index");
        }
    }
}

Controllers/ProductController.cs
using BuildingShopFront.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace BuildingShopFront.Controllers
{
    public class ProductController : Controller
    {
        private readonly HttpClient _httpClient;
        public ProductController(HttpClient httpClient)
        {
            _httpClient = httpClient;
        }
        public async Task<IActionResult> Index(int page=1)
        {
            await LoadCategories();
            return View(await GetData("","",page));
        }
        public async Task<IActionResult> Search(string? sortOrder,
            string? searchString, int page = 1)
        {
            return PartialView("_ProductsTable",
                await GetData("", searchString, page));
        }
        private async Task<object> GetData(
            string? sortOrder, string? searchString, int page = 1)
        {
            //var response = await _httpClient.GetAsync("api/Product");
            //response.EnsureSuccessStatusCode();
            //var content = await response.Content.ReadAsStringAsync();
            //var data = JsonConvert.DeserializeObject
            //    <List<Product>>(content);
            //return data;
            var response = await _httpClient
                .GetAsync("api/Product/sort" +
                $"?sortOrder={sortOrder}&searchString={searchString}&page={page}");
            response.EnsureSuccessStatusCode();
            var content=await response.Content.ReadAsStringAsync();
            JObject json= JObject.Parse(content);
            List<Product> products = new List<Product>();
            foreach (var item in json["items"])
            {
                products.Add(JsonConvert.DeserializeObject
                    <Product>(item.ToString()));
            }
            ViewBag.CurrentPage = json["currentPage"];
            ViewBag.TotalPages = json["totalPages"];
            ViewBag.TotalCount = json["totalCount"];
            await LoadCategories();
            return products;
        }
        public async Task LoadCategories()
        {
            var response = await _httpClient.GetAsync("api/ProductCategory");
            response.EnsureSuccessStatusCode();
            var content=await response.Content.ReadAsStringAsync();
            var data = JsonConvert.DeserializeObject
                <List<ProductCategory>>(content);
            ViewBag.Categories = new SelectList(data, "Id", "Name");
        }
        
        public async Task<IActionResult> Add(string name,
            int count, int categoryId)
        {
            if (!string.IsNullOrEmpty(name) && count > 0 && categoryId > 0)
            {
                var requestData = new
                {
                    name = name,
                    count = count,
                    categoryId = categoryId
                };
                var content = JsonContent.Create(requestData);
                var response = await _httpClient.PostAsync
                    ("api/Product", content);
                response.EnsureSuccessStatusCode();
            }
            return PartialView("_ProductsTable", await GetData("",""));
        }

        public async Task<IActionResult> Update(long id,string name,
            int count, int categoryId)
        {
            if (!string.IsNullOrEmpty(name) && count > 0 && categoryId > 0)
            {
                var requestData = new
                {
                    id = id,
                    name = name,
                    count = count,
                    categoryId = categoryId
                };
                var content = JsonContent.Create(requestData);
                var response = await _httpClient.PutAsync
                    ("api/Product", content);
                response.EnsureSuccessStatusCode();
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(long id)
        {
            var response = await _httpClient.DeleteAsync
                ($"api/Product/{id}");
            response.EnsureSuccessStatusCode();
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BuildingShopFront</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BuildingShopFront.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BuildingShopFront</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProductCategory" asp-action="Index">Категории товаров</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Товары</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-sm">
        <main role="main">
            <br />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - BuildingShopFront - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>